### ISSUE TITLE
fix ilastik object detection

### ISSUE THREAD

**Issue by wrgr** [openconnectome/macho#16]
Stuart reports that it's not working and is a bug beyond OCP.

**Comment by wrgr** [comment]
This now works.  Will require new classifiers, it seems...

**Comment by jovo** [comment]
like, there is a LONI demo using ilastik for cell detection?

On Thu, Oct 15, 2015 at 8:23 PM, William Gray notifications@github.com
wrote:

> This now works. Will require new classifiers, it seems...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/macho/issues/16#issuecomment-148559924
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by wrgr** [comment]
yessir. Hoping it will exist for SFN, but if not, will be in October.

Right now we do mitochondria, but it's an identical workflow.  Boundaries
and scalability are outside of this prototype, but will need to be
addressed (separate issues, perhaps).

There was an ilastik bug that the developers helped fix for running in
headless mode.  Seems that the old classifiers may not work though
(backwards compatibility).

Worst case we'll need to retrain, which should be mostly not horrible.

Best,
Will

On Thu, Oct 15, 2015 at 8:36 PM, joshua vogelstein <notifications@github.com

**Comment by wrgr** [comment]
Fixed!  Ilastik pixel and object detection fully integrated for cluster, local, or AMI processing.
